config/routes.rb
ExerciseApp::Application.routes.draw do
	resources :users
	
	resources :sessions, only: [:new, :create, :destroy]
	
	match '/signup', to: 'users#new'
	match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
	get   '/login', :to => 'sessions#new', :as => :login
	match '/auth/:provider/callback', :to => 'sessions#create'
	match '/auth/failure', :to => 'sessions#failure'
	resources :categories do
		collection do
			get :picture
		end
		member do
      get :likepage
    end
	end
	match '/search' => 'categories#search'
	
	resources :glossaries do
		member do
			get :expand
			get :collapse
		end
	end
	
	resources :optional_accessories do
		member do
			get :expand
			get :collapse
		end
	end
 	
 	resources :general_tips do
		member do
			get :expand
			get :collapse
		end
	end
 	
	resources :exercises do
		member do
			get :expand
			get :collapse
      get :likepage
		end
		collection do
			get :data
			get :media_display
		end
	end

	resources :videos do
		member do
			get :display
		end
	end
	
	resources :exercise_pictures  do
		member do
			get :display
		end
	end
	
	resources :workouts do
		member do
      get :likepage
    end
	end
	match '/signup',  to: 'users#new'
  match '/home', to: 'pages#home'
	root to: 'categories#index'
end

app/models/workout.rb
class Workout < ActiveRecord::Base
	attr_accessible :name
	has_many :workout_exercises, :foreign_key => "workout_id",
                                   			 :class_name => "ExerciseWorkout",
                                   			 :dependent => :destroy
  has_many :exercises, :through => :workout_exercises
	default_scope order: 'workouts.id DESC'
	
  def included_exercise?(exercise)
    workout_exercises.find_by_exercise_id(exercise)
  end

  def include_exercise!(exercise)
    workout_exercises.create!(:exercise_id => exercise.id)
  end
  
  def include_exercise_id!(exercise_id)
    workout_exercises.create!(:exercise_id => exercise_id)
  end
  
	def exclude_exercise!(exercise)
    workout_exercises.find_by_exercise_id(exercise).destroy
  end
end

app/controllers/workout_controller.rb
class WorkoutsController < ApplicationController
  
  def index
    @title = "All Workouts"
    @workouts = Workout.all
  end
  
  def show
  	@workout = Workout.find(params[:id])
  	@title = @workout.name + " | Rubberbanditz Exercise Library"
  end
  
  def edit
  	@workout = Workout.find(params[:id])
  	@title = "Edit Workout"
  end
  
  def update
    @workout = Workout.find(params[:id])
    if @workout.update_attributes(params[:workout])
      flash[:success] = "Profile updated."
    	redirect_to workouts_path
    else
      @title = "Edit Workout"
      render 'edit'
    end
  end

	def destroy
		Workout.find(params[:id]).destroy
    flash[:success] = "Workout destroyed."
    redirect_to workouts_path
  end
  
  def new
  	@workout = Workout.new
  	@title = "New Workout"
  end
  
  def create
    @workout = Workout.new(params[:workout])
    if @workout.save
      redirect_to workouts_path
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  
  def index
    render 'categories/index'
  end
  
  def show
		@workout = Workout.find(params[:id])
		respond_to do |format|
			format.html
			format.js
		end
  end
  
  def likepage
		@workout = Workout.find(params[:id])
		render :action => 'likepage', :layout => false
  end
  
  def edit
  	@workout = Workout.find(params[:id])
  	@title = "Edit Workout"
  end
  
  def update
    @workout = Workout.find(params[:id])
    if @workout.update_attributes(params[:workout])
      flash[:success] = "Profile updated."
    	redirect_to workouts_path
    else
      @title = "Edit Workout"
      render 'edit'
    end
  end

	def destroy
		Workout.find(params[:id]).destroy
    flash[:success] = "Workout destroyed."
    redirect_to workouts_path
  end
  
  def new
  	@workout = Workout.new
  	@title = "New Workout"
  end
  
  def create
    @workout = Workout.new(params[:workout])
    if @workout.save
      redirect_to workouts_path
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  
end

app/views/workouts/_title.html.erb
<div class="catimage">
<%= image_tag "Vectoredlogo.png" %>
</div>
<div class="dright" style="left:210px">
	<h1><%= workout.name.upcase %></h1>
	<%= workout.sets %> sets / <%= workout.reps %> reps <br />
	<%= workout.per_week %> times per week <br />
	<%= workout.duration %> <br />
	tempo: <%= workout.tempo %><br />
-If you do 20 reps and don’t feel fatigued, its too light.<br />
<div class="fb-like" data-href="<%= likepage_workout_url(workout) %>" data-send="true" data-width="450" data-show-faces="true"></div>
</div>
<script>
$('div.fb-like').attr('data-width',$('.dright').width()-15)
</script>

app/views/workouts/_workout.html.erb
<%= link_to workout.name, workout_path(workout), :remote => true, :id => "wo#{workout.id}" %><br/>

app/views/workouts/display.js.erb
$("div.sidebar a").removeClass("highlight");
$("a#wo<%= @workout.id %>").addClass("highlight");
$("div.descbar").show();
$("div.exercises").css("top","150px");
$("div.descbar").html("<%= escape_javascript(render('workouts/title', :workout => @workout)) %>");
$("table.exercises").html("<%= escape_javascript(render(@exercises)) %>");

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>

<%= form_for(@workout) do |f| %>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="actions">
	<%= f.submit "Save" %>
</div>
<% end %>

app/views/workouts/index.html.erb
<table class="all">
	<tr>
		<td>
			<div class="sidebar">
				<%= render @workouts %>
			</div>
		</td>
		<td>
		<div class="exercises">
				<%= render @workouts.first.exercises %></div>
		</td>
	</tr>
</table>

app/views/workouts/likepage.html.erb
<!DOCTYPE html>
<html xmlns:og="http://ogp.me/ns#">
  <head>
    <title><%= @workout.name %></title>
		<meta property="fb:app_id" content="299584876770579"/>
		<meta property="fb:admins" content="JasonMcMains"/ > 
		<meta property="og:title" content="<%= @workout.name %>"/>
		<meta property="og:type" content="website"/>
		<meta property="og:site_name" content="Rubberbanditz Exercise App"/ >
		<meta property="og:url" content="<%= likepage_workout_path(@workout) %>"/>
		<meta property="og:image" content="<%= 'assets/Vectoredlogo.png' %>" />
		<meta property="og:description" content="This is one of Rubberbanditz great workouts!"/>
  </head>
  <body>
<script>
  window.location = "<%= workout_path(@workout) %>";
</script>
  </body>
</html>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= form_for(@workout) do |f| %>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="actions">
	<%= f.submit "Save" %>
</div>
<% end %>

app/views/workouts/show.html.erb
<div class="descbar">
	<%= render('workouts/title', :workout => @workout) %>
</div>
<div class="exercises" style="top:150px">
	<table class="exercises"><%= render @workout.exercises %></table>
		<div class="results"></div>
</div>

<script>
$("div.sidebar a").removeClass("highlight");
$("a#wo<%= @workout.id %>").addClass("highlight");
</script>

app/views/workouts/show.js.erb
$("div.sidebar a").removeClass("highlight");
$("a#wo<%= @workout.id %>").addClass("highlight");
$("div.descbar").show();
$("div.results").hide();
$("div.exercises").css("top","150px");
$("div.descbar").html("<%= escape_javascript(render('workouts/title', :workout => @workout)) %>");
$("table.exercises").html("<%= escape_javascript(render(@workout.exercises)) %>");
window.history.replaceState("","","<%= workout_path(@workout) %>");
FB.XFBML.parse($(".dright")[0]);
document.title = "<%= @workout.name  + ' | Rubberbanditz Exercise Library' %>"