config/routes.rb
ExerciseApp::Application.routes.draw do
	resources :users
	
	resources :sessions, only: [:new, :create, :destroy]
	
	match '/signup', to: 'users#new'
	match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
	get   '/login', :to => 'sessions#new', :as => :login
	match '/auth/:provider/callback', :to => 'sessions#create'
	match '/auth/failure', :to => 'sessions#failure'
	resources :categories do
		collection do
			get :picture
		end
		member do
      get :likepage
    end
	end
	match '/search' => 'categories#search'
	
	resources :glossaries do
		member do
			get :expand
			get :collapse
		end
	end
	
	resources :optional_accessories do
		member do
			get :expand
			get :collapse
		end
	end
 	
 	resources :general_tips do
		member do
			get :expand
			get :collapse
		end
	end
 	
	resources :exercises do
		member do
			get :expand
			get :collapse
      get :likepage
		end
		collection do
			get :data
			get :media_display
		end
	end

	resources :videos do
		member do
			get :display
		end
	end
	
	resources :exercise_pictures  do
		member do
			get :display
		end
	end
	
	resources :workouts do
		member do
      get :likepage
    end
	end
	match '/signup',  to: 'users#new'
  match '/home', to: 'pages#home'
	root to: 'categories#index'
end

app/models/video.rb
class Video < ActiveRecord::Base
	attr_accessible :location
  belongs_to :exercise
  
  validates :exercise_id, :presence => true
  
  def get_image
  	"http://img.youtube.com/vi/" + self.location + "/default.jpg"
  end
  
  def get_embed
  	"http://www.youtube.com/embed/" + self.location
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  def index
    @title = "All Videos"
    @videos = Video.all
  end
  
  def display
		@video = Video.find(params[:id])
  	respond_to do |format|
			format.js
		end
	end
    
  def show
  	@video = Video.find(params[:id])
  end
  
  def edit
  	@video = Video.find(params[:id])
  	@title = "Edit Video"
  end
  
  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(params[:video])
      flash[:success] = "Profile updated."
    	redirect_to videos_path
    else
      @title = "Edit Video"
      render 'edit'
    end
  end

	def destroy
		Video.find(params[:id]).destroy
    flash[:success] = "Video destroyed."
    redirect_to videos_path
  end
  
  def new
  	@video = Video.new
  	@title = "New Video"
  end
  
  def create
    @video = Video.new(params[:video])
    if @video.save
      redirect_to videos_path
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  
end

app/views/videos/_video.html.erb
<li>
<iframe width="420" height="315" src="http://www.youtube.com/embed/<%= video.get_number(video) %>" frameborder="0" allowfullscreen></iframe><br />
<%= link_to video.location %>
</li>

app/views/videos/display.js.erb
$("div.enlarged<%= @video.exercise.id %>").html("<iframe class='youtube' width='350' height='267' src='<%= @video.get_embed %>' frameborder='0' allowfullscreen></iframe>")
$("div.scroll img").removeClass("highlight");
$("div.scroll img.v<%= @video.id %>").addClass("highlight");

app/views/videos/index.html.erb
<h1>All Videos</h1>
<ul class="videos">
  <%= render @videos %>
</ul>

<%= link_to 'New Videos', new_video_path %>

app/views/videos/show.html.erb
<iframe width="420" height="315" src="http://www.youtube.com/embed/<%= @video.get_number(@video) %>" frameborder="0" allowfullscreen></iframe>