config/routes.rb
ExerciseApp::Application.routes.draw do
	resources :users
	
	resources :sessions, only: [:new, :create, :destroy]
	
	match '/signup', to: 'users#new'
	match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
	get   '/login', :to => 'sessions#new', :as => :login
	match '/auth/:provider/callback', :to => 'sessions#create'
	match '/auth/failure', :to => 'sessions#failure'
	resources :categories do
		collection do
			get :picture
		end
		member do
      get :likepage
    end
	end
	match '/search' => 'categories#search'
	
	resources :glossaries do
		member do
			get :expand
			get :collapse
		end
	end
	
	resources :optional_accessories do
		member do
			get :expand
			get :collapse
		end
	end
 	
 	resources :general_tips do
		member do
			get :expand
			get :collapse
		end
	end
 	
	resources :exercises do
		member do
			get :expand
			get :collapse
      get :likepage
		end
		collection do
			get :data
			get :media_display
		end
	end

	resources :videos do
		member do
			get :display
		end
	end
	
	resources :exercise_pictures  do
		member do
			get :display
		end
	end
	
	resources :workouts do
		member do
      get :likepage
    end
	end
	match '/signup',  to: 'users#new'
  match '/home', to: 'pages#home'
	root to: 'categories#index'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base

	validates :name, :presence => true
	
  has_many :exercise_categories, :foreign_key => "exercise_id", :dependent => :destroy
  has_many :categories, :through => :exercise_categories
  accepts_nested_attributes_for :exercise_categories, :reject_if => :all_blank, :allow_destroy => true
    
	has_many :exercise_muscles, :foreign_key => "exercise_id", :dependent => :destroy
  has_many :muscles, :through => :exercise_muscles
  accepts_nested_attributes_for :exercise_muscles, :reject_if => :all_blank, :allow_destroy => true
    
    
  has_many :exercise_accessories, :foreign_key => "exercise_id",
                                 :dependent => :destroy
  has_many :accessories, :through => :exercise_accessories
  accepts_nested_attributes_for :exercise_accessories, :reject_if => :all_blank, :allow_destroy => true
  
  has_many :exercise_positions, :foreign_key => "exercise_id",
                                 :dependent => :destroy
  has_many :positions, :through => :exercise_positions
  accepts_nested_attributes_for :exercise_positions, :reject_if => :all_blank, :allow_destroy => true
  
 	has_many :exercise_heights, :foreign_key => "exercise_id",
                                 :dependent => :destroy
  has_many :heights, :through => :exercise_heights
  accepts_nested_attributes_for :exercise_heights, :reject_if => :all_blank, :allow_destroy => true
  
  has_many :exercise_forces, :foreign_key => "exercise_id",
                                 :dependent => :destroy
  has_many :forces, :through => :exercise_forces
 	accepts_nested_attributes_for :exercise_forces, :reject_if => :all_blank, :allow_destroy => true
  
  has_many :exercise_posts, :foreign_key => "exercise_id",
                                 :dependent => :destroy
  has_many :posts, :through => :exercise_posts
  accepts_nested_attributes_for :exercise_posts, :reject_if => :all_blank, :allow_destroy => true
  
  has_many :exercise_workouts, :foreign_key => "exercise_id",
                                 :dependent => :destroy
  has_many :workouts, :through => :exercise_workouts
  accepts_nested_attributes_for :exercise_workouts, :reject_if => :all_blank, :allow_destroy => true
  
  has_many :tips, :dependent => :destroy
  accepts_nested_attributes_for :tips, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
  has_many :variations, :dependent => :destroy
  accepts_nested_attributes_for :variations, :reject_if => :all_blank, :allow_destroy => true
  
  has_many :exercise_pictures, :foreign_key => "exercise_id",
                           		 :dependent => :destroy
  accepts_nested_attributes_for :exercise_pictures, :reject_if => :all_blank, :allow_destroy => true
  has_many :videos, :dependent => :destroy
  accepts_nested_attributes_for :videos, :reject_if => :all_blank, :allow_destroy => true
 	
  #Categories
  def included_category?(category)
    exercise_categories.find_by_category_id(category)
  end

  def include_category!(category)
    exercise_categories.create!(:category_id => category.id)
  end
  
  def include_category_id!(category_id)
    exercise_categories.create!(:category_id => category_id)
  end
  
	def exclude_category!(category)
    exercise_categories.find_by_category_id(category).destroy
  end
  
  #Accessories
  def included_accessory?(accessory)
    exercise_accessories.find_by_accessory_id(accessory)
  end

  def include_accessory!(accessory)
    exercise_accessories.create!(:accessory_id => accessory.id)
  end
  
  def include_accessory_id!(accessory_id)
    exercise_accessories.create!(:accessory_id => accessory_id)
  end
  
	def exclude_accessory!(accessory)
    exercise_accessories.find_by_accessory_id(accessory).destroy
  end
  
  def primary_accessory?(accessory_id)
  	exercise_accessories.find_by_accessory_id(accessory_id).primary
  end  
  
  #Positions
  def included_position?(position)
    exercise_positions.find_by_position_id(position)
  end

  def include_position!(position)
    exercise_positions.create!(:position_id => position.id)
  end
  
  def include_position_id!(position_id)
    exercise_positions.create!(:position_id => position_id)
  end
  
	def exclude_position!(position)
    exercise_positions.find_by_position_id(position).destroy
  end
  
  #Anchor Point Heights
  def included_height?(height)
    exercise_heights.find_by_height_id(height)
  end

  def include_height!(height)
    exercise_heights.create!(:height_id => height.id)
  end
  
  def include_height_id!(height_id)
    exercise_heights.create!(:height_id => height_id)
  end
  
	def exclude_height!(height)
    exercise_heights.find_by_height_id(height).destroy
  end
  
  #Target Muscles
  def included_muscle?(muscle)
    exercise_muscles.find_by_muscle_id(muscle)
  end

  def include_muscle!(muscle)
    exercise_muscles.create!(:muscle_id => muscle.id)
  end
  
  def include_muscle_id!(muscle_id)
    exercise_muscles.create!(:muscle_id => muscle_id)
  end
  
	def exclude_muscle!(muscle)
    exercise_muscles.find_by_muscle_id(muscle).destroy
  end
  
  def toggle_primary!(muscle_id)
  	exercise_muscles.find_by_muscle_id(muscle_id).toggle!(:primary)
  end
  
  def primary_muscle?(muscle_id)
  	exercise_muscles.find_by_muscle_id(muscle_id).primary
  end  
  
  #Forces
  def included_force?(force)
    exercise_forces.find_by_force_id(force)
  end

  def include_force!(force)
    exercise_forces.create!(:force_id => force.id)
  end
  
  def include_force_id!(force_id)
    exercise_forces.create!(:force_id => force_id)
  end
  
	def exclude_force!(force)
    exercise_forces.find_by_force_id(force).destroy
  end
  
 	#Posts
  def included_post?(post)
    exercise_posts.find_by_post_id(post)
  end

  def include_post!(post)
    exercise_posts.create!(:post_id => post.id)
  end
  
  def include_post_id!(post_id)
    exercise_posts.create!(:post_id => post_id)
  end
  
	def exclude_post!(post)
    exercise_posts.find_by_post_id(post).destroy
  end
  
  def self.search(search)
  	if search
  		all(include: [:categories, :tips, :variations, :muscles, :posts, :heights, :forces, :positions, :accessories], conditions: ['(exercises.name LIKE ? OR exercises.description LIKE ? OR categories.name LIKE ? OR tips.content LIKE ? OR variations.content LIKE ? OR target_muscles.name LIKE ? OR posts.name LIKE ? OR anchor_point_heights.name LIKE ? OR forces.name LIKE ? OR positions.name LIKE ? OR optional_accessories.name LIKE ?) AND exercises.display = ?',"%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%", true])
  	else
  		return find(:all)
  	end
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	def media_display
		@exercises = Exercise.all
		render layout: false
	end
	
  def expand
  	if params[:id].blank?
  		@exercise = Exercise.new
  		Category.all.count.times do
				categories = @exercise.exercise_categories.build
			end
			TargetMuscle.all.count.times do
				tm = @exercise.exercise_muscles.build
			end
			Post.all.count.times do
				p = @exercise.exercise_posts.build
			end
			AnchorPointHeight.all.count.times do
				aph = @exercise.exercise_heights.build
			end
			Force.all.count.times do
				f = @exercise.exercise_forces.build
			end
			Position.all.count.times do
				p = @exercise.exercise_positions.build
			end
			OptionalAccessory.all.count.times do
				oa = @exercise.exercise_accessories.build
			end
			3.times do
				tips = @exercise.tips.build
			end
			3.times do
				variation = @exercise.variations.build
			end
  	else
			@exercise = Exercise.find(params[:id])
			respond_to do |format|
				format.js
			end
		end
  end
  
  def collapse
  	@exercise = Exercise.find(params[:id])
  	respond_to do |format|
			format.html { redirect_to @exercise }
			format.js
		end
  end
  
  require 'csv'
  def data
		csv = CSV.generate(col_sep: "\t") do |csv|
			csv << ["Name", "Description", "Category", "workouts", "Tips", "Variations", "Target Muscles", "Post", "Anchor Point Height", "force", "Positions","videos","pictures"]
			Exercise.all.each do |ex|
				if ex.display
					name = ex.name
					desc = ex.description
					cats = ex.categories.map(&:name).join("|")
					workouts = ex.workouts.map(&:name).join("|")
					tips = ex.tips.map(&:content).join("|")
					variations = ex.variations.map(&:content).join("|")
					muscles = ex.muscles.map(&:name).join("|")
					posts = ex.posts.map(&:name).join("|")
					heights = ex.heights.map(&:name).join("|")
					forces = ex.forces.map(&:name).join("|")
					positions = ex.positions.map(&:name).join("|")
					videos = ex.videos.map(&:get_embed).join("|")
					pics = ex.exercise_pictures.map(&:get_site).join("|")
					csv << [name,desc,cats,workouts,tips,variations,muscles,posts,heights,forces,positions,videos,pics]
				end
			end
		end
		send_data csv, type: 'text/csv', filename: "exercise_data.csv"
  end
  
  def likepage
		@exercise = Exercise.find(params[:id])
		render :action => 'likepage', :layout => false
  end
  
  def show
  	@exercise = Exercise.find(params[:id])
  	@title = @exercise.name + " | Rubberbanditz Exercise Library"
  end

  def edit
  	@exercise = Exercise.find(params[:id])
  	@title = "Edit Exercise"
  	@exercise.videos.build
  	@exercise.exercise_pictures.build
  	@exercise.tips.build
 		@exercise.variations.build
 		respond_to do |format|
			format.html
			format.js
		end
  end

  def update
  	@exercise = Exercise.find(params[:id])
  	if @exercise.update_attributes(params[:exercise])
      redirect_to @exercise
    else
      @title = "Error"
      render 'new'
    end
  end
  
	def destroy
		Exercise.find(params[:id]).destroy
    flash[:success] = "Exercise destroyed."
    redirect_to root_path
  end
  
  def create
  	@exercise = Exercise.new(params[:exercise])
    if @exercise.save
      redirect_to @exercise
    else
      render 'new'
    end
  end
  
  def new
  	@exercise = Exercise.new
  	3.times do
  		tips = @exercise.tips.build
  	end
  	3.times do
  		variation = @exercise.variations.build
  	end
  	@exercise.videos.build
  	@exercise.exercise_pictures.build
  end
  
  def index
  	@title = "Exercise Search"
  	@exercises = Exercise.search(params[:search])
  	respond_to do |format|
			format.html
			format.js
		end
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_edit.html.erb
	<%= form_for(exercise) do |f| %>
		<div class="field">
			<%= f.label :name %> : <%= f.text_field :name %><br />
		</div>
		<span class="category">
		Categories: 
		<% Category.all.each do |cat| %>
			<%= check_box_tag "exercise[category_ids][]", cat.id, exercise.category_ids.include?(cat.id) %> <%= cat.name %>
		<% end %>
		<br>
		<%= f.check_box :display %> display<br>
		</span>

		<table class="allinfo" color="white">
		<tr id="left">
			<td>
				<span class="description">Description:<br />
				<%= f.text_area :description, size: "60x12" %><br /><br /></span>
					<span class="tips">Tips:
					<%= f.fields_for :tips do |builder| %>
						<%= render "tip_fields", :f => builder %>
					<% end %>
					<p><%= link_to_add_fields "Add Tip", f, :tips %></p>
					</span><br>
					<span class="variations">Variations:
					<%= f.fields_for :variations do |builder| %>
						<%= render "variation_fields", :f => builder %>
					<% end %>
					<p><%= link_to_add_fields "Add Variation", f, :variations %></p></span>
			</td>
			<td class="tright">
			<span class="videos">Videos:
			<%= f.fields_for :videos do |builder| %>
				<%= render "video_fields", :f => builder %>
			<% end %>
			<p><%= link_to_add_fields "Add Video", f, :videos %></p><br>
			<span class="images">Images:
			<%= f.fields_for :exercise_pictures do |builder| %>
				<%= render "exercise_picture_fields", :f => builder %>
			<% end %>
			<p><%= link_to_add_fields "Add Image", f, :exercise_pictures %></p><br>
			</span>
			Info:
					<table class="information">
						<tr class="titles">
							<td title="bold signifies primary muscle(s) used; others signify secondary muscle(s) used">TARGET MUSCLES</td>
							<td>POST</td>
							<td title="Roughly, how high the band should be fixed relative to your body A.P. = Anchor Point)">A.P. HEIGHT</td>
						</tr>
						<tr class="values">
							<td title="bold signifies primary muscle(s) used; others signify secondary muscle(s) used">
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
									<% TargetMuscle.all.each do |tm| %>
										<%= check_box_tag "exercise[muscle_ids][]", tm.id, exercise.muscle_ids.include?(tm.id) %> <%= tm.name %><br>
			 						<% end %>
		 						</div>
							</td>
							<td>
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
									<% Post.all.each do |post| %>
										<%= check_box_tag "exercise[post_ids][]", post.id, exercise.post_ids.include?(post.id) %> <%= post.name %><br>
			 						<% end %>
		 						</div>
							</td>
							<td title="Roughly, how high the band should be fixed relative to your body A.P. = Anchor Point (Please note that many glossary terms are italicized.)">
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
									<% AnchorPointHeight.all.each do |anchor| %>
										<%= check_box_tag "exercise[height_ids][]", anchor.id, exercise.height_ids.include?(anchor.id) %> <%= anchor.name %><br>
			 						<% end %>
		 						</div>
							</td>
						</tr>
						<tr class="titles">
							<td>FORCE</td>
							<td>POSITIONS</td>
							<td title="BOLD ACCESSORIES signify our recommendation, ALL = any option can function">OPTIONAL ACCESSORIES</td>
						</tr>
						<tr class="values">
							<td>
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
									<% Force.all.each do |force| %>
										<%= check_box_tag "exercise[force_ids][]", force.id, exercise.force_ids.include?(force.id) %> <%= force.name %><br>
			 						<% end %>
								</div>
							</td>
							<td>
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
									<% Position.all.each do |position| %>
										<%= check_box_tag "exercise[position_ids][]", position.id, exercise.position_ids.include?(position.id) %> <%= position.name %><br>
			 						<% end %>
		 						</div>
							</td>
							<td title="BOLD ACCESSORIES signify our recommendation, ALL = any option can function">
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
								<% OptionalAccessory.all.each do |accessory| %>
										<%= check_box_tag "exercise[accessory_ids][]", accessory.id, exercise.accessory_ids.include?(accessory.id) %> <%= accessory.name %><br>
			 						<% end %>
		 						</div>
							</td>
						</tr>
					</table>
			</td>
		</tr>
	</table>
		<div class="actions">
				<%= f.submit "Save" %>
			</div>
			<% if exercise.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(exercise.errors.count, "error") %> 
		      prohibited this exercise from being saved:</h2>
		  <p>There were problems with the following fields:</p>
		  <ul>
		  <% exercise.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	<% end %>
	<% end %>

app/views/exercises/_exercise_picture_fields.html.erb
<p class="fields">
Image: <%= f.text_field :picture %>
  <%= link_to_remove_fields "remove", f %>
</p>

app/views/exercises/edit.html.erb
<div class="descbar" style="display:none">
</div>
<div class="exercises" style="top:0px">
	<%= form_for(@exercise) do |f| %>
		<div class="field">
			<%= f.label :name %> : <%= f.text_field :name %><br />
		</div>
		<span class="category">
		Categories: 
		<% Category.all.each do |cat| %>
			<%= check_box_tag "exercise[category_ids][]", cat.id, @exercise.category_ids.include?(cat.id) %> <%= cat.name %>
		<% end %>
		<br>
		<%= f.check_box :display %> display<br>
		</span>

		<table class="allinfo" color="white">
		<tr id="left">
			<td>
				<span class="description">Description:<br />
				<%= f.text_area :description, size: "60x12" %><br /></span><br />
				<br />
					<span class="tips">Tips:
					<%= f.fields_for :tips do |builder| %>
						<%= render "tip_fields", :f => builder %>
					<% end %>
					<p><%= link_to_add_fields "Add Tip", f, :tips %></p>
					</span>
					<span class="variations">Variations:
					<%= f.fields_for :variations do |builder| %>
						<%= render "variation_fields", :f => builder %>
					<% end %>
					<p><%= link_to_add_fields "Add Variation", f, :variations %></p></span>
			</td>
			<td class="tright">
			<span class="videos">Videos:
			<%= f.fields_for :videos do |builder| %>
				<%= render "video_fields", :f => builder %>
			<% end %>
			<p><%= link_to_add_fields "Add Video", f, :videos %></p>
			<span class="images">Images:
			<%= f.fields_for :exercise_pictures do |builder| %>
				<%= render "exercise_picture_fields", :f => builder %>
			<% end %>
			<p><%= link_to_add_fields "Add Image", f, :exercise_pictures %></p>
			</span>
			Info:
					<table class="information">
						<tr class="titles">
							<td title="bold signifies primary muscle(s) used; others signify secondary muscle(s) used">TARGET MUSCLES</td>
							<td>POST</td>
							<td title="Roughly, how high the band should be fixed relative to your body A.P. = Anchor Point)">A.P. HEIGHT</td>
						</tr>
						<tr class="values">
							<td title="bold signifies primary muscle(s) used; others signify secondary muscle(s) used">
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
									<% TargetMuscle.all.each do |tm| %>
										<%= check_box_tag "exercise[muscle_ids][]", tm.id, @exercise.muscle_ids.include?(tm.id) %> <%= tm.name %><br>
			 						<% end %>
		 						</div>
							</td>
							<td>
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
									<% Post.all.each do |post| %>
										<%= check_box_tag "exercise[post_ids][]", post.id, @exercise.post_ids.include?(post.id) %> <%= post.name %><br>
			 						<% end %>
		 						</div>
							</td>
							<td title="Roughly, how high the band should be fixed relative to your body A.P. = Anchor Point (Please note that many glossary terms are italicized.)">
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
									<% AnchorPointHeight.all.each do |anchor| %>
										<%= check_box_tag "exercise[height_ids][]", anchor.id, @exercise.height_ids.include?(anchor.id) %> <%= anchor.name %><br>
			 						<% end %>
		 						</div>
							</td>
						</tr>
						<tr class="titles">
							<td>FORCE</td>
							<td>POSITIONS</td>
							<td title="BOLD ACCESSORIES signify our recommendation, ALL = any option can function">OPTIONAL ACCESSORIES</td>
						</tr>
						<tr class="values">
							<td>
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
									<% Force.all.each do |force| %>
										<%= check_box_tag "exercise[force_ids][]", force.id, @exercise.force_ids.include?(force.id) %> <%= force.name %><br>
			 						<% end %>
								</div>
							</td>
							<td>
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
									<% Position.all.each do |position| %>
										<%= check_box_tag "exercise[position_ids][]", position.id, @exercise.position_ids.include?(position.id) %> <%= position.name %><br>
			 						<% end %>
		 						</div>
							</td>
							<td title="BOLD ACCESSORIES signify our recommendation, ALL = any option can function">
								<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
								<% OptionalAccessory.all.each do |accessory| %>
										<%= check_box_tag "exercise[accessory_ids][]", accessory.id, @exercise.accessory_ids.include?(accessory.id) %> <%= accessory.name %><br>
			 						<% end %>
		 						</div>
							</td>
						</tr>
					</table>
			</td>
		</tr>
	</table>
		<div class="actions">
				<%= f.submit "Save" %>
			</div>
			<% if @exercise.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@exercise.errors.count, "error") %> 
		      prohibited this exercise from being saved:</h2>
		  <p>There were problems with the following fields:</p>
		  <ul>
		  <% @exercise.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	<% end %>
	<% end %>
</div>

app/views/exercises/new.html.erb
<div class="descbar" style="display:none">
</div>
<div class="exercises" style="top:0px">
<%= form_for(@exercise) do |f| %>
	<div class="field">
		<%= f.label :name %> : <%= f.text_field :name %><br />
	</div>
	<span class="category">
	Categories: 
	<%= hidden_field_tag "exercise[category_ids][]", nil %>
	<% Category.all.each do |cat| %>
		<%= check_box_tag "exercise[category_ids][]", cat.id %> <%= cat.name %>
	<% end %>
		<br>
	<%= f.check_box :display %> display<br>
	</span>
	<table class="allinfo" color="white">
	<tr id="left">
		<td>
			<span class="description">Description:<br />
			<%= f.text_area :description, size: "60x12" %><br /></span><br />
			<br />
				<span class="tips">Tips:
				<%= f.fields_for :tips do |builder| %>
					<%= render "tip_fields", :f => builder %>
				<% end %>
				<p><%= link_to_add_fields "Add Tip", f, :tips %></p>
				</span>
				<span class="variations">Variations:
				<%= f.fields_for :variations do |builder| %>
					<%= render "variation_fields", :f => builder %>
				<% end %>
				<p><%= link_to_add_fields "Add Variation", f, :variations %></p></span>
		</td>
		<td class="tright">
		<span class="videos">Videos:
		<%= f.fields_for :videos do |builder| %>
			<%= render "video_fields", :f => builder %>
		<% end %>
		<p><%= link_to_add_fields "Add Video", f, :videos %></p>
		<span class="images">Images:
		<%= f.fields_for :exercise_pictures do |builder| %>
			<%= render "exercise_picture_fields", :f => builder %>
		<% end %>
		<p><%= link_to_add_fields "Add Image", f, :exercise_pictures %></p>
		</span>
		Info:
				<table class="information">
					<tr class="titles">
						<td title="bold signifies primary muscle(s) used; others signify secondary muscle(s) used">TARGET MUSCLES</td>
						<td>POST</td>
						<td title="Roughly, how high the band should be fixed relative to your body A.P. = Anchor Point)">A.P. HEIGHT</td>
					</tr>
					<tr class="values">
						<td title="bold signifies primary muscle(s) used; others signify secondary muscle(s) used">
							<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
								<%= hidden_field_tag "exercise[muscle_ids][]", nil %>
								<% TargetMuscle.all.each do |tm| %>
									<%= check_box_tag "exercise[muscle_ids][]", tm.id %> <%= tm.name %><br>
		 						<% end %>
	 						</div>
						</td>
						<td>
							<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
								<%= hidden_field_tag "exercise[post_ids][]", nil %>
								<% Post.all.each do |post| %>
									<%= check_box_tag "exercise[post_ids][]", post.id %> <%= post.name %><br>
		 						<% end %>
	 						</div>
						</td>
						<td title="Roughly, how high the band should be fixed relative to your body A.P. = Anchor Point (Please note that many glossary terms are italicized.)">
							<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
								<%= hidden_field_tag "exercise[height_ids][]", nil %>
								<% AnchorPointHeight.all.each do |anchor| %>
									<%= check_box_tag "exercise[height_ids][]", anchor.id %> <%= anchor.name %><br>
		 						<% end %>
	 						</div>
						</td>
					</tr>
					<tr class="titles">
						<td>FORCE</td>
						<td>POSITIONS</td>
						<td title="BOLD ACCESSORIES signify our recommendation, ALL = any option can function">OPTIONAL ACCESSORIES</td>
					</tr>
					<tr class="values">
						<td>
							<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
								<%= hidden_field_tag "exercise[force_ids][]", nil %>
								<% Force.all.each do |force| %>
									<%= check_box_tag "exercise[force_ids][]", force.id %> <%= force.name %><br>
		 						<% end %>
							</div>
						</td>
						<td>
							<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
		 						<%= hidden_field_tag "exercise[position_ids][]", nil %>
								<% Position.all.each do |p| %>
									<%= check_box_tag "exercise[position_ids][]", p.id %> <%= p.name %><br>
		 						<% end %>
	 						</div>
						</td>
						<td title="BOLD ACCESSORIES signify our recommendation, ALL = any option can function">
							<div style ="height: 100px;width:150px;overflow: auto;text-align:left">
							<%= hidden_field_tag "exercise[accessory_ids][]", nil %>
							<% OptionalAccessory.all.each do |accessory| %>
									<%= check_box_tag "exercise[accessory_ids][]", accessory.id %> <%= accessory.name %><br>
		 						<% end %>
	 						</div>
						</td>
					</tr>
				</table>
		</td>
	</tr>
</table>
	<div class="actions">
			<%= f.submit "Save" %>
		</div>
		<% if @exercise.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@exercise.errors.count, "error") %> 
        prohibited this exercise from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @exercise.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% end %>

</div>